# Generated by Django 5.0 on 2023-12-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_estado_description_alter_pais_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='pais',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
