# Generated by Django 5.0 on 2023-12-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_estado_description_alter_pais_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='codigo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pais',
            name='codigo',
            field=models.IntegerField(),
        ),
    ]
