# Generated by Django 5.0 on 2023-12-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_estado_codigo_alter_pais_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
